name: Deploy to ProFreeHost

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ftpupload.net
          username: ezyro_41652401   # your ProFreeHost FTP username
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./htdocs         # repo root goes into /htdocs
